server:
  port: 8084

spring:
  application:
    name: Razorpay
  data:
    mongodb:
      host: localhost
      port: 27017
      database: multikart_razorpay

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
