server:
  port: 8085

spring:
  application:
    name: Product
  data:
    mongodb:
      host: localhost
      port: 27017
      database: multiKart_product

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
